services:
  postgres:
    image: postgres:16-alpine
    container_name: devdock-postgres
    environment:
      POSTGRES_USER: devdock
      POSTGRES_PASSWORD: devdock
      POSTGRES_DB: devdock
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devdock -d devdock"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: devdock-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  mailhog:
    image: mailhog/mailhog:latest
    container_name: devdock-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  pgdata:
  redisdata:
